version: '3.8'

services:
  go:
    image: golang:1.17-alpine
    tty: true
    restart: always
    working_dir: /cloudprober
    user: ${UID:-0}:${GID:-0}
    environment:
      HOME: /tmp
    ports:
    - 9313:9313
    volumes:
    - .:/cloudprober
    - ${GOPATH:-~/go}:/go
